version: "3.5"
services:
  etcd:
    hostname: etcd
    image: bitnami/etcd:3
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    privileged: true
    volumes:
      - "/data/Development/volume/etcd/data:/opt/bitnami/etcd/data"
    environment:
      - "ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379"
      - "ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379"
      - "ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380"
      - "ETCD_INITIAL_ADVERTISE_PEER_URLS=http://0.0.0.0:2380"
      - "ALLOW_NONE_AUTHENTICATION=yes"
      - "ETCD_INITIAL_CLUSTER=node1=http://0.0.0.0:2380"
      - "ETCD_NAME=node1"
      - "ETCD_DATA_DIR=/opt/bitnami/etcd/data"
    ports:
      - "2379:2379"
      - "2380:2380"
    networks:
      monitor:
        ipv4_address: 172.19.0.4

  agent01:
    build:
      context: .
      dockerfile: agent01_dockerfile
    hostname: agent01
    container_name: agent01
    ports:
      - "11000:11000"
    networks:
      monitor:
        ipv4_address: 172.19.0.2
    restart: on-failure
    depends_on:
      - etcd

  agent02:
    build:
      context: .
      dockerfile: agent02_dockerfile
    hostname: agent02
    container_name: agent02
    ports:
      - "11001:11001"
    networks:
      monitor:
        ipv4_address: 172.19.0.3
    restart: on-failure
    depends_on:
      - etcd
networks:
  monitor:
    name: monitor
    ipam:
      config:
        - subnet: 172.19.0.0/24
          gateway: 172.19.0.1
    driver: bridge