version: "3.5"
services:
  #zk配置
  zoo1:
    image: zookeeper
    hostname: zoo1
    container_name: zoo1
    restart: unless-stopped
    ports:
      - 2181:2181
    volumes:
      - "/data/Development/volume/zkcluster/zoo1/data:/data"
      - "/data/Development/volume/zkcluster/zoo1/datalog:/datalog"
    environment:
      ZOO_PORT: 2181
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    networks:
      monitor:
        ipv4_address: 172.19.0.12
  zoo2:
    image: zookeeper
    hostname: zoo2
    container_name: zoo2
    restart: unless-stopped
    ports:
      - 2182:2181
    volumes:
      - "/data/Development/volume/zkcluster/zoo2/data:/data"
      - "/data/Development/volume/volume/zkcluster/zoo2/datalog:/datalog"
    environment:
      ZOO_MY_ID: 2
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181
    networks:
      monitor:
        ipv4_address: 172.19.0.13
  zoo3:
    image: zookeeper
    hostname: zoo3
    container_name: zoo3
    restart: unless-stopped
    ports:
      - 2183:2181
    volumes:
      - "/data/Development/volume/zkcluster/zoo3/data:/data"
      - "/data/Development/volume/zkcluster/zoo3/datalog:/datalog"
    environment:
      ZOO_MY_ID: 3
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
    networks:
      monitor:
        ipv4_address: 172.19.0.14
  #kafka 配置
  # 222.200.105.85要替换为宿主机ip
  kafka1:
    image: wurstmeister/kafka
    restart: on-failure
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://222.200.105.85:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_HOST_NAME: kafka1
      KAFKA_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://:9092
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181,zoo2:2181,zoo3:2181"
      KAFKA_BROKER_ID: 1
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    volumes:
      - /data/Development/volume/kfkluster/kafka1/logs:/kafka
    networks:
      monitor:
        ipv4_address: 172.19.0.15
  kafka2:
    image: wurstmeister/kafka
    restart: on-failure
    hostname: kafka2
    container_name: kafka2
    ports:
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka2:19093,LISTENER_DOCKER_EXTERNAL://222.200.105.85:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_HOST_NAME: kafka2
      KAFKA_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka2:19093,LISTENER_DOCKER_EXTERNAL://:9093
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181,zoo2:2181,zoo3:2181"
      KAFKA_BROKER_ID: 2
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    volumes:
      - /data/Development/volume/kfkluster/kafka2/logs:/kafka
    networks:
      monitor:
        ipv4_address: 172.19.0.16
  kafka3:
    image: wurstmeister/kafka
    restart: on-failure
    hostname: kafka3
    container_name: kafka3
    ports:
      - "9094:9094"
    environment:
      #      175.178.91.147
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka3:19094,LISTENER_DOCKER_EXTERNAL://222.200.105.85:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_HOST_NAME: kafka3
      KAFKA_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka3:19094,LISTENER_DOCKER_EXTERNAL://:9094
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181,zoo2:2181,zoo3:2181"
      KAFKA_BROKER_ID: 3
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    volumes:
      - /data/Development/volume/kfkluster/kafka3/logs:/kafka
    networks:
      monitor:
        ipv4_address: 172.19.0.17
#自定义网络
networks:
  monitor:
    name: monitor
    ipam:
      config:
        - subnet: 172.19.0.0/24 #子网
          gateway: 172.19.0.1
    driver: bridge #网桥模式